"""add owner to lists

Revision ID: 7c716f1c9428
Revises: be057435dfbe
Create Date: 2024-01-16 19:42:48.743891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c716f1c9428'
down_revision: Union[str, None] = 'be057435dfbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lists', sa.Column('owner_id', sa.Integer(), nullable=True, default=1))
    op.create_foreign_key(None, 'lists', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lists', type_='foreignkey')
    op.drop_column('lists', 'owner_id')
    # ### end Alembic commands ###
